// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grid': string;
  'gridItem': string;
  'gridItemPlaceholder': string;
}
export const cssExports: CssExports;
export default cssExports;
