// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'profile': string;
  'profileHeader': string;
  'profileHeader__back': string;
  'profileHeader__usernamPlaceholder': string;
  'profileHeader__username': string;
  'profileParams': string;
  'profileParams__item': string;
  'profileParams__itemPlaceholder': string;
  'profile__image': string;
  'profile__left': string;
  'profile__link': string;
  'profile__linkPlaceholder': string;
  'profile__right': string;
}
export const cssExports: CssExports;
export default cssExports;
